# prod: cashback_bot
services:
  bot_pay:
    build: .
    container_name: bot_pay
    command: ["/app/.venv/bin/python", "run.py"]
    env_file:
      - .env        
    volumes:
      - ./logs:/app/logs
    restart: always

