# prod: cashback_bot
services:
  cashback_bot:
    build: .
    container_name: cashback_bot
    command: ["/app/.venv/bin/python", "run.py"]
    env_file:
      - .env        
    volumes:
      - ./logs:/app/logs
    restart: always

